### ISSUE TITLE
환경 변수 설정되지 않았을 시 적절한 에러 메시지 혹은 지시사항 안내

### ISSUE THREAD

**Issue by echoja** [Mapps-unit/backend#16]
새롭게 프로젝트 실행시키는 개발자 입장에서 혼란스러울 수 있음.

이하 환경변수 설정하지 않았을 때 뜨는 에러
```
/Users/th.kim/Desktop/onit-backend/node_modules/sequelize/lib/sequelize.js:281
      throw new Error('Dialect needs to be explicitly supplied as of v4.0.0');
      ^

Error: Dialect needs to be explicitly supplied as of v4.0.0
    at new Sequelize (/Users/th.kim/Desktop/onit-backend/node_modules/sequelize/lib/sequelize.js:281:13)
    at Object.<anonymous> (/Users/th.kim/Desktop/onit-backend/models/index.js:13:19)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/th.kim/Desktop/onit-backend/app.js:10:21)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
[nodemon] app crashed - waiting for file changes before starting...

```

우선순위가 중요한 업무는 아님

**Comment by echoja** [comment]
세팅하는 법을 Readme.md 파일에 적는 걸로 해결하기.
